# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/

language: cpp

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

# enable using trusty beta ubuntu
sudo: required
dist: trusty

# install build requirements
before_install:  
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then 
      pip install --user codecov;
      sudo apt-get update -qq;
      sudo apt-get install -y libsdl2-dev;
      sudo apt-get install -y libglew-dev;
      export DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then 
      pip install --user codecov;
      brew update;
      brew upgrade cmake;
      brew install sdl2;
      brew install glew;
    fi

env:
  - MAKE_TARGET=install CMAKE_BUILD_TYPE=Debug
  - MAKE_TARGET=test CMAKE_BUILD_TYPE=Debug
  - MAKE_TARGET=install CMAKE_BUILD_TYPE=Release
  - MAKE_TARGET=test CMAKE_BUILD_TYPE=Release

before_script:
  - cd build
  # only generate coverage report if building test and cmake build type is Debug
  - if [ "$MAKE_TARGET" == "test" ] && [ "$CMAKE_BUILD_TYPE" == "Debug" ]; then
      cmake -Dbuild_test=ON -Dgen_coverage=ON -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE ..;
    elif [ "$MAKE_TARGET" == "test" ]; then
      cmake -Dbuild_test=ON -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE ..;
    else
      cmake -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE ..;
    fi

script: 
  - make
  - CTEST_OUTPUT_ON_FAILURE=1 make $MAKE_TARGET
  - if [ "$MAKE_TARGET" == "install" ]; then
      cd ..; 
      ./myapp -y;
    fi

after_success:
  # only upload coverage report in test
  - if [ "$MAKE_TARGET" == "test" ]; then
      codecov;
    fi