language: cpp

compiler:
	- gcc
	- clang

before_install:
	- sudo apt-get update -qq
	- sudo apt-get install -y libsdl2-dev
	- sudo apt-get install -y libglew-dev

before_script:
	- cd build
	- cmake ../src

script: make install && cd.. && ./myapp

os:
	- linux
	- osx