# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/

language: cpp

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

# enable using trusty beta ubuntu
sudo: required
dist: trusty
  
before_install:  
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq; fi
  #- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository ppa:zoogie/sdl2-snapshots -y; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libsdl2-dev; fi
  #- if [ "$TRAVIS_OS_NAME" == "linux" ]; then bash libsdl2_for_travis.sh; fi  
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libglew-dev; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install sdl2; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install glew; fi  
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
  
before_script:
  - cd build
  - cmake -Dbuild_test=ON ..

env:
  - MAKE_TARGET=install
  - MAKE_TARGET=test
  
script: 
  - make
  - make $MAKE_TARGET
  - if [ "$MAKE_TARGET" == "install" ]; then cd ..; fi	
  - if [ "$MAKE_TARGET" == "install" ]; then ./myapp -y; fi
