clone_depth: 5

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - cmd: cd C:\projects
  - cmd: set PATH=C:\projects\anjing\windows\bin;C:\Python27\Scripts;C:\projects\flex_bison;%PATH%;
  - cmd: pip install Mako
  - cmd: curl -fsSL -o mesa.tar.gz ftp://ftp.freedesktop.org/pub/mesa/12.0.3/mesa-12.0.3.tar.gz
  - cmd: curl -fsSL -o scons.zip http://superb-sea2.dl.sourceforge.net/project/scons/scons/2.5.0/scons-2.5.0.zip
  - cmd: curl -fsSLk -o flex_bison.zip https://github.com/lexxmark/winflexbison/releases/download/v2.5.6/win_flex_bison-2.5.6.zip
  - cmd: dir
  - cmd: 7z x -oscons -y scons.zip
  - cmd: cd scons\scons-2.5.0
  - cmd: python setup.py install
  - cmd: cd ..\..
  - cmd: 7z x -oflex_bison -y flex_bison.zip
  - cmd: cd flex_bison
  - cmd: cp win_bison.exe bison.exe
  - cmd: cp win_flex.exe flex.exe
  - cmd: cd ..
  - cmd: 7z x -omesa.tar -y mesa.tar.gz
  - cmd: cd mesa.tar
  - cmd: 7z x -ttar -omesa -y mesa.tar
  - cmd: cd mesa\mesa-12.0.3
  - cmd: scons
  - cmd: cd C:\projects\mesa.tar\mesa\mesa-12.0.3\build\windows-x86-debug\gallium\targets\libgl-gdi
  - cmd: cp opengl32.dll C:\projects\anjing\build\test\gfx\%CONFIGURATION% #use opengl32.dll on all the tests

before_build:
  - cmd: cd C:\projects\anjing
  - cmd: cd build
  - cmd: cmake -Dbuild_test=ON ..

configuration:
  - Debug
  - Release
  
build:
  parallel: true
  project: C:\projects\anjing\build\anjing.sln

#Appveyor only supports opengl up to 1.1, so disable this until we find out how to make appveyor support opengl 3.3
test_script:
 - cmd: cd C:\projects\anjing\build
 - cmd: echo conf = %CONFIGURATION%
 - cmd: ctest -C %CONFIGURATION% --output-on-failure -V

# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
