clone_depth: 5

install:
  - cmd: set PATH=%PATH%;C:\projects\anjing\windows\bin

before_build:
  - cmd: cd C:\projects\anjing
  - cmd: cd build
  - cmd: cmake -Dbuild_test=ON ..

configuration:
  - Debug
  - Release
  
build:
  parallel: true
  project: C:\projects\anjing\build\anjing.sln

#Appveyor only supports opengl up to 1.1, so disable this until we find out how to make appveyor support opengl 3.3
#test_script:
#  - cmd: cd C:\projects\anjing\build
#  - cmd: echo conf = %CONFIGURATION%
#  - cmd: ctest -C %CONFIGURATION% --output-on-failure -V