clone_depth: 5

before_build:
  - cmd: cd C:\projects\anjing
  - cmd: cd build
  - cmd: cmake -Dbuild_test=ON ..
  
configuration:
  - Debug
  - Release
  
build:
  parallel: true
  project: C:\projects\anjing\build\RUN_TESTS.vcxproj
  
