clone_depth: 5

install:
  - cmd: set PATH=%PATH%;C:\projects\anjing\windows\bin

before_build:
  - cmd: cd C:\projects\anjing
  - cmd: cd build
  - cmd: cmake -Dbuild_test=ON ..

configuration:
  - Debug
  - Release
  
#build_script:
#  - cmd: msbuild C:\projects\anjing\build\ALL_BUILD.vcxproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
#  - cmd: msbuild C:\projects\anjing\build\test\app\test_app.vcxproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

build:
  parallel: true
  project: C:\projects\anjing\build\anjing.sln

test_script:
  - cmd: cd C:\projects\anjing\build
  - cmd: ctest -C %CONFIGURATION% --output-on-failure -V