clone_depth: 5

before_build:
  - cmd: cd C:\projects\anjing
  - cmd: cd build
  - cmd: cmake -Dbuild_test=ON ..
  - cmd: msbuild C:\projects\anjing\build\ALL_BUILD.vcxproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

configuration:
  - Debug
  - Release
  
build:
  parallel: true
  project: C:\projects\anjing\build\test\app\test_app.vcxproj
  
after_build:
  - cmd: cd C:\projects\anjing\build\test\app\%CONFIGURATION%
  - cmd: test_app.exe